Repository WebChatting/chatting, pull requests merged in 2023-04, with the labels that each got.

#70 ci(docker-compose): fix build & deploy process
  Jenkinsfile
  Makefile
Labels: bug

#76 feat: integrate swagger
  README.md
  pom.xml
  src/main/java/com/sxrekord/chatting/config/SwaggerConfig.java
  src/main/java/com/sxrekord/chatting/controller/UserController.java
  src/main/resources/application.yml
Labels: enhancement, todo

#77 Feat/blacklist
  src/main/java/com/sxrekord/chatting/common/RedisKey.java
  src/main/java/com/sxrekord/chatting/exception/GlobalExceptionHandler.java
  src/main/java/com/sxrekord/chatting/interceptor/UserAuthInterceptor.java
  src/main/java/com/sxrekord/chatting/service/impl/UserServiceImpl.java
  src/main/java/com/sxrekord/chatting/util/JwtTokenUtils.java
  src/main/java/com/sxrekord/chatting/util/RedisUtils.java
  src/test/java/com/sxrekord/chatting/util/JwtTokenUtilTest.java
  src/test/java/com/sxrekord/chatting/util/RedisUtilsTest.java
Labels: enhancement, todo

#79 rsa实现前后端加密传输重要数据
  src/main/java/com/sxrekord/chatting/controller/CommonController.java
  src/main/java/com/sxrekord/chatting/service/impl/UserServiceImpl.java
  src/main/java/com/sxrekord/chatting/util/SecurityUtils.java
  src/main/resources/application.yml
  src/test/java/com/sxrekord/chatting/service/UserServiceTest.java
  src/test/java/com/sxrekord/chatting/util/SecurityUtilsTest.java
Labels: enhancement

#88 fix: fix file upload error on linux
  src/main/java/com/sxrekord/chatting/config/WebMvcConfig.java
  src/main/java/com/sxrekord/chatting/service/impl/FileServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/sxrekord/chatting/util/FileUtilsTest.java
Labels: bug
