Repository WebChatting/chatting, pull requests merged in 2023-03, with the labels that each got.

#29 refactor: refactor chatting database
  src/main/java/com/sxrekord/chatting/dao/UserDao.java
  src/main/java/com/sxrekord/chatting/model/po/Group.java
  src/main/java/com/sxrekord/chatting/model/po/ImageContent.java
  src/main/java/com/sxrekord/chatting/model/po/Message.java
  src/main/java/com/sxrekord/chatting/model/po/Relation.java
  src/main/java/com/sxrekord/chatting/model/po/User.java
  src/main/java/com/sxrekord/chatting/service/impl/ChatServiceImpl.java
  src/main/java/com/sxrekord/chatting/service/impl/UserServiceImpl.java
  src/main/resources/mapper/group-mapper.xml
  src/main/resources/mapper/message_mapper.xml
  src/main/resources/mapper/user-mapper.xml
  src/main/resources/sql/data.sql
  src/main/resources/sql/schema.sql
Labels: enhancement

#31 fix(security): use dedicated user instead of root for database access
  .github/workflows/ci.yml
  README.md
  src/main/resources/application.yml
Labels: bug, enhancement

#36 ci(deploy): add Jenkinsfile for deployment
  Jenkinsfile
Labels: enhancement

#37 ci(deply): fix not restart after reboot
  Jenkinsfile
Labels: bug

#47 fix database design
  src/main/resources/sql/schema.sql
Labels: bug

#49 Test/interfacev2
  src/main/java/com/sxrekord/chatting/controller/RelationController.java
  src/main/java/com/sxrekord/chatting/dao/GroupDao.java
  src/main/java/com/sxrekord/chatting/dao/RelationDao.java
  src/main/java/com/sxrekord/chatting/model/po/Relation.java
  src/main/java/com/sxrekord/chatting/service/RelationService.java
  src/main/java/com/sxrekord/chatting/service/impl/GroupServiceImpl.java
  src/main/java/com/sxrekord/chatting/service/impl/RelationServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/group-mapper.xml
  src/main/resources/mapper/relation-mapper.xml
  src/main/resources/sql/data.sql
  src/main/resources/sql/query.sql
  src/test/java/com/sxrekord/chatting/dao/GroupDaoTest.java
  src/test/java/com/sxrekord/chatting/dao/RelationDaoTest.java
  src/test/java/com/sxrekord/chatting/service/GroupServiceTest.java
  src/test/java/com/sxrekord/chatting/service/RelationServiceTest.java
Labels: enhancement

#58 perf(docker): build jar outside of docker
  Dockerfile
  Jenkinsfile
  Makefile
Labels: enhancement

#60 Feat/ws
  src/main/java/com/sxrekord/chatting/service/ChatService.java
  src/main/java/com/sxrekord/chatting/service/impl/ChatServiceImpl.java
  src/main/java/com/sxrekord/chatting/util/ChatType.java
  src/main/java/com/sxrekord/chatting/websocket/WebSocketServerHandler.java
  src/test/java/com/sxrekord/chatting/model/vo/ResponseJsonTest.java
Labels: enhancement

#62 perf: use mybatis-plus replace mybatis
  pom.xml
  src/main/resources/application.yml
Labels: enhancement, todo
